version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app.php"
  relay: pipes
  env:
    - XDEBUG_SESSION: 1

http:
  address: 0.0.0.0:8090
  middleware: [ "gzip", "static" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    num_workers: 1
    supervisor:
      max_worker_memory: 100

jobs:
  consume: [ ]
  pool:
    num_workers: 2
    supervisor:
      max_worker_memory: 100

kv:
  local:
    driver: memory
    config:
      interval: 60
  redis:
    driver: redis
    config:
      addrs:
        - localhost:6379
status:
  # Host and port to listen on (eg.: `127.0.0.1:2114`). Use the following URL: http://127.0.0.1:2114/health?plugin=http
  # Multiple plugins must be separated using "&" - http://127.0.0.1:2114/health?plugin=http&plugin=rpc where "http" and
  # "rpc" are active (connected) plugins.
  #
  # This option is required.
  address: 127.0.0.1:8082

  # Response status code if a requested plugin not ready to handle requests
  # Valid for both /health and /ready endpoints
  #
  # Default: 503
  unavailable_status_code: 503

#grpc:
#  listen: "tcp://0.0.0.0:9001"
#  proto:
#    - "first.proto"

metrics:
  address: localhost:2112
