version: "3.8"

# possible since 3.4
x-php:
  &php
  build:
    dockerfile: .docker/php/Dockerfile
    context: ./
    target: app_php
  depends_on:
    postgres:
      condition: service_healthy
    minio:
      condition: service_healthy
    gotenberg:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  application:
    <<: *php
    command: "/app/rr serve -c .rr.yaml"

  cron:
    <<: *php
    command: supercronic /etc/supercronic/podlodka

  postgres:
    image: postgres:15.2-alpine3.17

  gotenberg:
    image: thecodingmachine/gotenberg:7.8

  redis:
    image: redis:7-alpine

  minio:
    image: minio/minio:RELEASE.2021-06-09T18-51-39Z
